version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    entrypoint:
      - python
      - app.py
    environment:
      FLASK_DEBUG: 1
      FLASK_ENV: development
  redis:
    image: "redislabs/redistimeseries"
    container_name: redisTimeSeries
    hostname: RedisTimeSeries
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"
